color: null
fieldLayouts:
  21033e13-39f5-41f6-869c-7c3df48ba1c6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'CTA Text'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9e9574ec-9560-4a85-b3b0-e6c15e9d2e90
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7dc4f949-dd98-417d-a37c-631f3b090645
            handle: ctaUrl
            includeInCards: false
            instructions: null
            label: 'CTA URL'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 030d16f4-e797-4d00-ba3c-82e5bc6183d8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3f0309d9-88d4-4633-aa36-ee17b84263ca
        userCondition: null
handle: cta
hasTitleField: true
icon: ''
name: CTA
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{entryId}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
