color: null
fieldLayouts:
  663e360d-ca54-4c47-9d7f-81e1fb263ca7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 75e0d68b-ca52-42dd-bdd4-575790340beb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9a3d509f-0817-4939-ba9d-7bc072e7a2a6 # Plain Text
            handle: headline
            includeInCards: false
            instructions: 'Headline for the homepage hero area.'
            label: Headline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3c178d4-11bb-4341-8021-8de0f261ca86
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9a3d509f-0817-4939-ba9d-7bc072e7a2a6 # Plain Text
            handle: tagline
            includeInCards: false
            instructions: 'Appears under the hero image headline.'
            label: Tagline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e10526f-a184-43e1-99a7-db47188609a3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa3a842d-5920-4d3a-8ab8-907575c75b42 # Image
            handle: heroImage
            includeInCards: false
            instructions: 'Image that appears as background of hero area.'
            label: 'Hero Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f5f15de-828e-4cf5-a5dc-a4040a82f4f2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9bad91aa-b92a-4327-85b1-c25b6124d092
        userCondition: null
handle: homepage
hasTitleField: false
icon: house
name: Homepage
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{headline}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
