color: null
fieldLayouts:
  bc705f0d-95da-4f7d-b26f-822a6229b675:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ccf7b5ed-5e01-4e05-a8e5-b137756d3d05
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9a3d509f-0817-4939-ba9d-7bc072e7a2a6 # Plain Text
            handle: tagline
            includeInCards: false
            instructions: null
            label: 'Page Tagline'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b80ac72-19d2-4a22-8dd4-004b222688cf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 41fc6ea2-fba5-4f60-bada-751d0dd08557
        userCondition: null
handle: listingPage
hasTitleField: true
icon: list-radio
name: 'Listing Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
