color: null
fieldLayouts:
  436ebd1d-85e5-46e9-8bf5-b09599b56599:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5c037142-83ac-470c-a324-c9fd13402cc2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c6d99cf5-e79d-447e-bbfd-299ebd88db00 # Content Builder CK
            handle: locationContent
            includeInCards: false
            instructions: null
            label: 'Location Content'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d344b847-14b5-4e52-be1c-7be5a1e5a3cb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f7467145-3196-4d29-ba2f-d665cef1885a # Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64399a07-62ad-4fca-987f-6cdb7d5bdd87
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2afd7f9f-3984-4283-9fcc-1ee303dafa02
        userCondition: null
handle: locations
hasTitleField: true
icon: map
name: Locations
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
