columnSuffix: null
handle: richTextContent
instructions: null
name: 'Rich Text Content'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: f0b04f8f-2d8b-4385-8b15-8c41f7bac65a # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
